[2023-01-10T20:42:49.698-0500] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: walmart-ml-workflow.train manual__2023-01-11T01:42:24.943325+00:00 [queued]>
[2023-01-10T20:42:49.710-0500] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: walmart-ml-workflow.train manual__2023-01-11T01:42:24.943325+00:00 [queued]>
[2023-01-10T20:42:49.711-0500] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-10T20:42:49.711-0500] {taskinstance.py:1284} INFO - Starting attempt 1 of 4
[2023-01-10T20:42:49.711-0500] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-10T20:42:49.721-0500] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): train> on 2023-01-11 01:42:24.943325+00:00
[2023-01-10T20:42:49.724-0500] {standard_task_runner.py:55} INFO - Started process 4066 to run task
[2023-01-10T20:42:49.730-0500] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'walmart-ml-workflow', 'train', 'manual__2023-01-11T01:42:24.943325+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/walmart-ml-workflow.py', '--cfg-path', '/var/folders/lc/0q_5vmf5385c78mr7v2ntch00000gn/T/tmpb35k8v2_']
[2023-01-10T20:42:49.734-0500] {standard_task_runner.py:83} INFO - Job 16: Subtask train
[2023-01-10T20:42:49.791-0500] {task_command.py:389} INFO - Running <TaskInstance: walmart-ml-workflow.train manual__2023-01-11T01:42:24.943325+00:00 [running]> on host toyosis-macbook-pro.local
[2023-01-10T20:42:49.968-0500] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=toyosibamidele@gmail.com
AIRFLOW_CTX_DAG_OWNER=Toyosi Bami
AIRFLOW_CTX_DAG_ID=walmart-ml-workflow
AIRFLOW_CTX_TASK_ID=train
AIRFLOW_CTX_EXECUTION_DATE=2023-01-11T01:42:24.943325+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-11T01:42:24.943325+00:00
[2023-01-10T20:42:49.970-0500] {subprocess.py:63} INFO - Tmp dir root location: 
 /var/folders/lc/0q_5vmf5385c78mr7v2ntch00000gn/T
[2023-01-10T20:42:49.971-0500] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 ~/airflow/scripts/train.py']
[2023-01-10T20:42:49.977-0500] {subprocess.py:86} INFO - Output:
[2023-01-10T20:42:50.974-0500] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-01-10T20:42:50.975-0500] {subprocess.py:93} INFO -   File "/Users/toyosibamidele/airflow/scripts/train.py", line 19, in <module>
[2023-01-10T20:42:50.976-0500] {subprocess.py:93} INFO -     df = pd.read_csv(path.joinpath('dat/train-store1.csv'))
[2023-01-10T20:42:50.977-0500] {subprocess.py:93} INFO -   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/util/_decorators.py", line 211, in wrapper
[2023-01-10T20:42:50.978-0500] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2023-01-10T20:42:50.979-0500] {subprocess.py:93} INFO -   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/util/_decorators.py", line 331, in wrapper
[2023-01-10T20:42:50.980-0500] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2023-01-10T20:42:50.981-0500] {subprocess.py:93} INFO -   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
[2023-01-10T20:42:50.981-0500] {subprocess.py:93} INFO -     return _read(filepath_or_buffer, kwds)
[2023-01-10T20:42:50.982-0500] {subprocess.py:93} INFO -   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 605, in _read
[2023-01-10T20:42:50.983-0500] {subprocess.py:93} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2023-01-10T20:42:50.983-0500] {subprocess.py:93} INFO -   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
[2023-01-10T20:42:50.984-0500] {subprocess.py:93} INFO -     self._engine = self._make_engine(f, self.engine)
[2023-01-10T20:42:50.985-0500] {subprocess.py:93} INFO -   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
[2023-01-10T20:42:50.986-0500] {subprocess.py:93} INFO -     self.handles = get_handle(
[2023-01-10T20:42:50.986-0500] {subprocess.py:93} INFO -   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/io/common.py", line 856, in get_handle
[2023-01-10T20:42:50.987-0500] {subprocess.py:93} INFO -     handle = open(
[2023-01-10T20:42:50.987-0500] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/Users/toyosibamidele/airflow/dat/train-store1.csv'
[2023-01-10T20:42:51.082-0500] {subprocess.py:97} INFO - Command exited with return code 1
[2023-01-10T20:42:51.092-0500] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-01-10T20:42:51.097-0500] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=walmart-ml-workflow, task_id=train, execution_date=20230111T014224, start_date=20230111T014249, end_date=20230111T014251
[2023-01-10T20:42:51.110-0500] {standard_task_runner.py:100} ERROR - Failed to execute job 16 for task train (Bash command failed. The command returned a non-zero exit code 1.; 4066)
[2023-01-10T20:42:51.143-0500] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-10T20:42:51.165-0500] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
