[2023-01-10T20:47:59.940-0500] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: walmart-ml-workflow.train manual__2023-01-11T01:42:24.943325+00:00 [queued]>
[2023-01-10T20:47:59.951-0500] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: walmart-ml-workflow.train manual__2023-01-11T01:42:24.943325+00:00 [queued]>
[2023-01-10T20:47:59.951-0500] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-10T20:47:59.951-0500] {taskinstance.py:1284} INFO - Starting attempt 2 of 4
[2023-01-10T20:47:59.951-0500] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-10T20:47:59.961-0500] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): train> on 2023-01-11 01:42:24.943325+00:00
[2023-01-10T20:47:59.964-0500] {standard_task_runner.py:55} INFO - Started process 4312 to run task
[2023-01-10T20:47:59.969-0500] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'walmart-ml-workflow', 'train', 'manual__2023-01-11T01:42:24.943325+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/walmart-ml-workflow.py', '--cfg-path', '/var/folders/lc/0q_5vmf5385c78mr7v2ntch00000gn/T/tmpikg2pa4a']
[2023-01-10T20:47:59.972-0500] {standard_task_runner.py:83} INFO - Job 19: Subtask train
[2023-01-10T20:48:00.034-0500] {task_command.py:389} INFO - Running <TaskInstance: walmart-ml-workflow.train manual__2023-01-11T01:42:24.943325+00:00 [running]> on host toyosis-macbook-pro.local
[2023-01-10T20:48:00.196-0500] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=toyosibamidele@gmail.com
AIRFLOW_CTX_DAG_OWNER=Toyosi Bami
AIRFLOW_CTX_DAG_ID=walmart-ml-workflow
AIRFLOW_CTX_TASK_ID=train
AIRFLOW_CTX_EXECUTION_DATE=2023-01-11T01:42:24.943325+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-11T01:42:24.943325+00:00
[2023-01-10T20:48:00.197-0500] {subprocess.py:63} INFO - Tmp dir root location: 
 /var/folders/lc/0q_5vmf5385c78mr7v2ntch00000gn/T
[2023-01-10T20:48:00.198-0500] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 ~/airflow/scripts/train.py']
[2023-01-10T20:48:00.204-0500] {subprocess.py:86} INFO - Output:
[2023-01-10T20:48:01.160-0500] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-01-10T20:48:01.161-0500] {subprocess.py:93} INFO -   File "/Users/toyosibamidele/airflow/scripts/train.py", line 19, in <module>
[2023-01-10T20:48:01.162-0500] {subprocess.py:93} INFO -     df = pd.read_csv(path.joinpath('dat/train-store1.csv'))
[2023-01-10T20:48:01.163-0500] {subprocess.py:93} INFO -   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/util/_decorators.py", line 211, in wrapper
[2023-01-10T20:48:01.163-0500] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2023-01-10T20:48:01.164-0500] {subprocess.py:93} INFO -   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/util/_decorators.py", line 331, in wrapper
[2023-01-10T20:48:01.164-0500] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2023-01-10T20:48:01.165-0500] {subprocess.py:93} INFO -   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
[2023-01-10T20:48:01.165-0500] {subprocess.py:93} INFO -     return _read(filepath_or_buffer, kwds)
[2023-01-10T20:48:01.166-0500] {subprocess.py:93} INFO -   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 605, in _read
[2023-01-10T20:48:01.166-0500] {subprocess.py:93} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2023-01-10T20:48:01.167-0500] {subprocess.py:93} INFO -   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
[2023-01-10T20:48:01.167-0500] {subprocess.py:93} INFO -     self._engine = self._make_engine(f, self.engine)
[2023-01-10T20:48:01.168-0500] {subprocess.py:93} INFO -   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
[2023-01-10T20:48:01.169-0500] {subprocess.py:93} INFO -     self.handles = get_handle(
[2023-01-10T20:48:01.169-0500] {subprocess.py:93} INFO -   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/io/common.py", line 856, in get_handle
[2023-01-10T20:48:01.171-0500] {subprocess.py:93} INFO -     handle = open(
[2023-01-10T20:48:01.172-0500] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/Users/toyosibamidele/airflow/dat/train-store1.csv'
[2023-01-10T20:48:01.277-0500] {subprocess.py:97} INFO - Command exited with return code 1
[2023-01-10T20:48:01.288-0500] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-01-10T20:48:01.292-0500] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=walmart-ml-workflow, task_id=train, execution_date=20230111T014224, start_date=20230111T014759, end_date=20230111T014801
[2023-01-10T20:48:01.305-0500] {standard_task_runner.py:100} ERROR - Failed to execute job 19 for task train (Bash command failed. The command returned a non-zero exit code 1.; 4312)
[2023-01-10T20:48:01.345-0500] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-10T20:48:01.360-0500] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
