[2023-01-09T16:47:10.557-0500] {processor.py:153} INFO - Started process (PID=39138) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T16:47:10.563-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T16:47:10.563-0500] {logging_mixin.py:137} INFO - [2023-01-09T16:47:10.563-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T16:47:10.616-0500] {logging_mixin.py:137} INFO - [2023-01-09T16:47:10.615-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T16:47:10.616-0500] {logging_mixin.py:137} INFO - [2023-01-09T16:47:10.616-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T16:47:10.616-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T16:47:11.275-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.718 seconds
[2023-01-09T16:49:07.953-0500] {processor.py:153} INFO - Started process (PID=39270) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T16:49:07.958-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T16:49:07.958-0500] {logging_mixin.py:137} INFO - [2023-01-09T16:49:07.958-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T16:49:08.007-0500] {logging_mixin.py:137} INFO - [2023-01-09T16:49:08.006-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T16:49:08.007-0500] {logging_mixin.py:137} INFO - [2023-01-09T16:49:08.007-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T16:49:08.007-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T16:49:08.743-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.791 seconds
[2023-01-09T16:52:00.557-0500] {processor.py:153} INFO - Started process (PID=39362) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T16:52:00.563-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T16:52:00.563-0500] {logging_mixin.py:137} INFO - [2023-01-09T16:52:00.563-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T16:52:00.611-0500] {logging_mixin.py:137} INFO - [2023-01-09T16:52:00.611-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T16:52:00.612-0500] {logging_mixin.py:137} INFO - [2023-01-09T16:52:00.612-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T16:52:00.612-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T16:52:01.221-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.664 seconds
[2023-01-09T16:54:46.757-0500] {processor.py:153} INFO - Started process (PID=39462) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T16:54:46.763-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T16:54:46.763-0500] {logging_mixin.py:137} INFO - [2023-01-09T16:54:46.763-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T16:54:46.806-0500] {logging_mixin.py:137} INFO - [2023-01-09T16:54:46.805-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T16:54:46.806-0500] {logging_mixin.py:137} INFO - [2023-01-09T16:54:46.806-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T16:54:46.806-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T16:54:47.569-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.812 seconds
[2023-01-09T16:57:38.665-0500] {processor.py:153} INFO - Started process (PID=40973) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T16:57:38.673-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T16:57:38.673-0500] {logging_mixin.py:137} INFO - [2023-01-09T16:57:38.673-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T16:57:38.717-0500] {logging_mixin.py:137} INFO - [2023-01-09T16:57:38.717-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T16:57:38.718-0500] {logging_mixin.py:137} INFO - [2023-01-09T16:57:38.717-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T16:57:38.718-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T16:57:39.321-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.656 seconds
[2023-01-09T17:00:24.881-0500] {processor.py:153} INFO - Started process (PID=41291) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:00:24.886-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T17:00:24.886-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:00:24.886-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:00:24.928-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:00:24.928-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T17:00:24.928-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:00:24.928-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T17:00:24.929-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:00:25.596-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.716 seconds
[2023-01-09T17:03:36.779-0500] {processor.py:153} INFO - Started process (PID=41539) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:03:36.785-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T17:03:36.785-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:03:36.785-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:03:36.839-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:03:36.838-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T17:03:36.839-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:03:36.839-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T17:03:36.840-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:03:37.545-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.766 seconds
[2023-01-09T17:06:37.059-0500] {processor.py:153} INFO - Started process (PID=41891) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:06:37.064-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T17:06:37.065-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:06:37.065-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:06:37.109-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:06:37.109-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T17:06:37.109-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:06:37.109-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T17:06:37.109-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:06:37.770-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.712 seconds
[2023-01-09T17:09:23.471-0500] {processor.py:153} INFO - Started process (PID=42153) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:09:23.476-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T17:09:23.476-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:09:23.476-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:09:23.521-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:09:23.521-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T17:09:23.522-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:09:23.522-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T17:09:23.522-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:09:24.218-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.748 seconds
[2023-01-09T17:12:08.036-0500] {processor.py:153} INFO - Started process (PID=42441) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:12:08.042-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T17:12:08.042-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:12:08.042-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:12:08.084-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:12:08.084-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T17:12:08.085-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:12:08.084-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T17:12:08.085-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:12:08.731-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.696 seconds
[2023-01-09T17:13:08.792-0500] {processor.py:153} INFO - Started process (PID=42544) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:13:08.805-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T17:13:08.806-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:13:08.806-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:13:08.858-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:13:08.857-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T17:13:08.858-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:13:08.858-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T17:13:08.858-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:13:10.974-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 2.183 seconds
[2023-01-09T17:14:53.758-0500] {processor.py:153} INFO - Started process (PID=42674) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:14:53.763-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T17:14:53.764-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:14:53.764-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:14:53.806-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:14:53.805-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T17:14:53.806-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:14:53.806-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T17:14:53.806-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:14:54.456-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.699 seconds
[2023-01-09T17:14:58.270-0500] {processor.py:153} INFO - Started process (PID=42680) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:14:58.275-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T17:14:58.275-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:14:58.275-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:14:58.318-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:14:58.318-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T17:14:58.318-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:14:58.318-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T17:14:58.319-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:14:58.989-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.720 seconds
[2023-01-09T17:17:26.806-0500] {processor.py:153} INFO - Started process (PID=43085) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:17:26.811-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T17:17:26.812-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:17:26.812-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:17:26.857-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:17:26.857-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T17:17:26.857-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:17:26.857-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T17:17:26.858-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:17:27.574-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.768 seconds
[2023-01-09T17:17:36.237-0500] {processor.py:153} INFO - Started process (PID=43148) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:17:36.242-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T17:17:36.242-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:17:36.242-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:17:36.286-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:17:36.285-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T17:17:36.286-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:17:36.286-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T17:17:36.286-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:17:36.922-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.685 seconds
[2023-01-09T17:19:57.905-0500] {processor.py:153} INFO - Started process (PID=43269) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:19:57.911-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T17:19:57.911-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:19:57.911-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:19:57.953-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:19:57.953-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T17:19:57.953-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:19:57.953-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T17:19:57.953-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:19:58.594-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.690 seconds
[2023-01-09T17:20:07.033-0500] {processor.py:153} INFO - Started process (PID=43276) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:20:07.038-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T17:20:07.039-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:20:07.038-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:20:07.079-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:20:07.078-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T17:20:07.079-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:20:07.079-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T17:20:07.079-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:20:07.753-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.720 seconds
[2023-01-09T17:22:29.144-0500] {processor.py:153} INFO - Started process (PID=43441) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:22:29.150-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T17:22:29.151-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:22:29.150-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:22:29.194-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:22:29.193-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T17:22:29.194-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:22:29.194-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T17:22:29.194-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:22:29.862-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.718 seconds
[2023-01-09T17:22:38.722-0500] {processor.py:153} INFO - Started process (PID=43448) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:22:38.726-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T17:22:38.727-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:22:38.727-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:22:38.767-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:22:38.766-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T17:22:38.767-0500] {logging_mixin.py:137} INFO - [2023-01-09T17:22:38.767-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T17:22:38.767-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T17:22:39.434-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.713 seconds
[2023-01-09T18:31:01.780-0500] {processor.py:153} INFO - Started process (PID=44377) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:31:01.780-0500] {processor.py:153} INFO - Started process (PID=44376) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:31:01.786-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T18:31:01.786-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T18:31:01.787-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:31:01.787-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:31:01.787-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:31:01.787-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:31:01.853-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:31:01.852-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T18:31:01.853-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:31:01.852-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T18:31:01.853-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:31:01.853-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T18:31:01.853-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:31:01.853-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T18:31:01.853-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:31:01.853-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:31:03.048-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 1.268 seconds
[2023-01-09T18:31:03.050-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 1.271 seconds
[2023-01-09T18:32:54.848-0500] {processor.py:153} INFO - Started process (PID=44581) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:32:54.848-0500] {processor.py:153} INFO - Started process (PID=44582) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:32:54.853-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T18:32:54.853-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T18:32:54.854-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:32:54.854-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:32:54.854-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:32:54.854-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:32:54.899-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:32:54.898-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T18:32:54.899-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:32:54.898-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T18:32:54.899-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:32:54.899-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T18:32:54.899-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:32:54.899-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T18:32:54.899-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:32:54.899-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:32:55.562-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.715 seconds
[2023-01-09T18:32:55.564-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.716 seconds
[2023-01-09T18:35:30.474-0500] {processor.py:153} INFO - Started process (PID=44724) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:35:30.480-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T18:35:30.480-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:35:30.480-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:35:30.528-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:35:30.527-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T18:35:30.528-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:35:30.528-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T18:35:30.528-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:35:31.271-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.798 seconds
[2023-01-09T18:35:36.490-0500] {processor.py:153} INFO - Started process (PID=44729) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:35:36.495-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T18:35:36.495-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:35:36.495-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:35:36.537-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:35:36.536-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T18:35:36.537-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:35:36.537-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T18:35:36.537-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:35:37.147-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.658 seconds
[2023-01-09T18:38:12.594-0500] {processor.py:153} INFO - Started process (PID=44874) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:38:12.599-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T18:38:12.600-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:38:12.599-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:38:12.642-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:38:12.642-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T18:38:12.642-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:38:12.642-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T18:38:12.642-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:38:13.272-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.678 seconds
[2023-01-09T18:38:14.241-0500] {processor.py:153} INFO - Started process (PID=44875) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:38:14.246-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T18:38:14.246-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:38:14.246-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:38:14.286-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:38:14.286-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T18:38:14.286-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:38:14.286-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T18:38:14.286-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:38:14.917-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.677 seconds
[2023-01-09T18:40:46.758-0500] {processor.py:153} INFO - Started process (PID=45105) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:40:46.763-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T18:40:46.764-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:40:46.763-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:40:46.811-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:40:46.811-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T18:40:46.811-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:40:46.811-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T18:40:46.812-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:40:47.520-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.763 seconds
[2023-01-09T18:40:52.056-0500] {processor.py:153} INFO - Started process (PID=45108) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:40:52.061-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T18:40:52.061-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:40:52.061-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:40:52.102-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:40:52.102-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T18:40:52.102-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:40:52.102-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T18:40:52.102-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:40:52.734-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.679 seconds
[2023-01-09T18:43:25.656-0500] {processor.py:153} INFO - Started process (PID=45248) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:43:25.662-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T18:43:25.662-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:43:25.662-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:43:25.706-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:43:25.706-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T18:43:25.706-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:43:25.706-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T18:43:25.706-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:43:26.316-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.660 seconds
[2023-01-09T18:43:31.265-0500] {processor.py:153} INFO - Started process (PID=45252) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:43:31.270-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T18:43:31.270-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:43:31.270-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:43:31.313-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:43:31.312-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T18:43:31.313-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:43:31.313-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T18:43:31.313-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:43:31.915-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.651 seconds
[2023-01-09T18:46:20.520-0500] {processor.py:153} INFO - Started process (PID=45490) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:46:20.525-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T18:46:20.526-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:46:20.526-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:46:20.570-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:46:20.570-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T18:46:20.571-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:46:20.571-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T18:46:20.571-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:46:21.415-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.895 seconds
[2023-01-09T18:46:29.323-0500] {processor.py:153} INFO - Started process (PID=45499) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:46:29.328-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T18:46:29.329-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:46:29.329-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:46:29.419-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:46:29.419-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T18:46:29.420-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:46:29.420-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T18:46:29.420-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:46:30.214-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.892 seconds
[2023-01-09T18:49:20.871-0500] {processor.py:153} INFO - Started process (PID=45704) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:49:20.880-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T18:49:20.880-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:49:20.880-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:49:20.935-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:49:20.935-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T18:49:20.935-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:49:20.935-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T18:49:20.936-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:49:21.837-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.966 seconds
[2023-01-09T18:49:31.746-0500] {processor.py:153} INFO - Started process (PID=45711) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:49:31.751-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T18:49:31.752-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:49:31.751-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:49:31.796-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:49:31.796-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T18:49:31.797-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:49:31.796-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T18:49:31.797-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:49:32.493-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.747 seconds
[2023-01-09T18:52:23.164-0500] {processor.py:153} INFO - Started process (PID=45880) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:52:23.171-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T18:52:23.172-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:52:23.172-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:52:23.237-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:52:23.237-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T18:52:23.238-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:52:23.238-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T18:52:23.238-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:52:24.727-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 1.567 seconds
[2023-01-09T18:52:35.513-0500] {processor.py:153} INFO - Started process (PID=45888) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:52:35.522-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T18:52:35.523-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:52:35.523-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:52:35.616-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:52:35.613-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T18:52:35.618-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:52:35.617-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T18:52:35.618-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:52:36.779-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 1.267 seconds
[2023-01-09T18:54:20.207-0500] {processor.py:153} INFO - Started process (PID=45951) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:54:20.221-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T18:54:20.222-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:54:20.222-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:54:20.304-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:54:20.303-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T18:54:20.304-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:54:20.304-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T18:54:20.304-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:54:21.312-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 1.111 seconds
[2023-01-09T18:56:35.195-0500] {processor.py:153} INFO - Started process (PID=46042) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:56:35.202-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T18:56:35.203-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:56:35.202-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:56:35.278-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:56:35.277-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T18:56:35.278-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:56:35.278-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T18:56:35.278-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:56:36.712-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 1.517 seconds
[2023-01-09T18:56:48.282-0500] {processor.py:153} INFO - Started process (PID=46052) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:56:48.290-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T18:56:48.291-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:56:48.291-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:56:48.373-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:56:48.373-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T18:56:48.374-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:56:48.374-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T18:56:48.374-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:56:49.832-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 1.552 seconds
[2023-01-09T18:59:05.684-0500] {processor.py:153} INFO - Started process (PID=46183) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:59:05.695-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T18:59:05.695-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:59:05.695-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:59:05.779-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:59:05.778-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T18:59:05.779-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:59:05.779-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T18:59:05.779-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:59:06.891-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 1.209 seconds
[2023-01-09T18:59:18.437-0500] {processor.py:153} INFO - Started process (PID=46190) to work on /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:59:18.442-0500] {processor.py:743} INFO - Processing file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-01-09T18:59:18.443-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:59:18.443-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:59:18.500-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:59:18.499-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-01-09T18:59:18.500-0500] {logging_mixin.py:137} INFO - [2023-01-09T18:59:18.500-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-01-09T18:59:18.500-0500] {processor.py:755} WARNING - No viable dags retrieved from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-01-09T18:59:19.453-0500] {processor.py:175} INFO - Processing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 1.017 seconds
